### ISSUE TITLE
AdaptiveViewGrid - Bug: Item size not updated on collection update

### ISSUE THREAD

**Issue by LostLogic** [LanceMcCarthy/UwpProjects#2] opened 2016-02-03 20:32 UTC
I have a pivot with two pivotitems.
Each PivotItem has an AdaptiveViewGrid.

This has created some interesting results.
When the Item collection is updated, the height of the items increase.
If the window size is changed after the item collection is updated, the size of the items in the AdaptiveViewGrid that was not in the pivot currently being viewed, the size has not been updated.

**Comment by LanceMcCarthy** [comment] 2016-02-03 23:35
I'm not able to reproduce the problem, I've attached a demo and followed your steps (you'll need to reference UwpHelpers.Controls to bring in AdaptiveGridView). 

In the demo, the **AppBarButton** will update the bound collection. If you switch between the PivotItems, the list items are all the proper sizes even after re-sizing and switching Pivots

[AdaptiveGridViewInPivot.zip](https://github.com/LanceMcCarthy/UwpProjects/files/116603/AdaptiveGridViewInPivot.zip)

**Comment by LostLogic** [comment] 2016-02-05 21:45
Hi Lance,

Sorry for going radio silent. I've been attending a seminar for the past days so no coding time. Attached is a project that demonstrates the issue. Please note: I am using Template 10, so that might be the issue, or I've setup my collections weird...

[AdaptiveGridViewInPivot.zip](https://github.com/LanceMcCarthy/UwpProjects/files/119908/AdaptiveGridViewInPivot.zip)

Edit:
How to produce the issue. View pivot item 1, then pivot item 2. Resize the window to a greater size, click the refresh button. Pivot item 2 is updated with the correct width, switch to pivot item 1, you can see it has not been updated until a new window resize is done

**Comment by LanceMcCarthy** [comment] 2016-05-14 17:07
This has been fixed as of latest update.

**Closed as completed by LanceMcCarthy** 2016-05-14 17:07 UTC
